routes/web.php
<?php

use App\Http\Controllers\AlbumController;
use App\Http\Controllers\ArtistController;
use App\Http\Controllers\PlaylistController;
use App\Http\Controllers\TrackController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/artist', [ArtistController::class, 'index'])->name('artist.index');
Route::get('/artist/{artist}', [ArtistController::class, 'show'])->name('artist.show');

Route::get('/album/{album}', [AlbumController::class, 'show'])->name('album.show');

Route::get('/track', [TrackController::class, 'index'])->name('track.index');
Route::get('/track/{track}', [TrackController::class, 'show'])->name('track.show');

Route::get('/playlist/{playlist}', [PlaylistController::class, 'show'])->name('playlist.show');

app/Models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Album extends Model
{
    use HasFactory;

    public function track(): HasMany
    {
        return $this->hasMany(Track::class);
    }

    public function artist(): BelongsTo
    {
        return $this->belongsTo(Artist::class);
    }
}

app/Models/Artist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Artist extends Model
{
    use HasFactory;
    public function album(): HasMany
    {
        return $this->hasMany(Album::class);
    }
}

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    use HasFactory;
}

app/Models/Playlist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Playlist extends Model
{
    use HasFactory;
    public function track(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Track::class);
    }
}

app/Models/Track.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Track extends Model
{
    use HasFactory;
    public function genre(): BelongsTo
    {
        return $this->belongsTo(Genre::class);
    }
    public function playlist(): BelongsToMany
    {
        return $this->belongsToMany(Playlist::class);
    }

    public function album(): BelongsTo
    {
        return $this->belongsTo(Album::class);
    }

    public function getMbAttribute()
    {
        return round($this->bytes /1024 /1024, 2);
    }

    public function getTimeAttribute()
    {
        return date('i:s', $this->milliseconds / 1000);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use App\Models\Artist;
use Illuminate\Http\Request;
use Illuminate\View\View;

class AlbumController extends Controller
{
    public function show(Album $album): View
    {
        $album->load('track', 'artist');
        return view('album.show')->with(['album' => $album]);
    }
}

app/Http/Controllers/ArtistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artist;
use Illuminate\Http\Request;
use App\Services\ArtistService;
use Illuminate\View\View;

class ArtistController extends Controller
{
    public function index()
    {
        $artists = Artist::all();

        return view('artists.index')->with(['artists' => $artists]);
    }

    /**
     * @param Artist $artist
     * @return View
     */
    public function show(Artist $artist): View
    {
        $artist->load('album');
        return view('artists.show')->with(['artist' => $artist]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GenreController extends Controller
{
    //
}

app/Http/Controllers/PlaylistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Playlist;
use Illuminate\Http\Request;
use Illuminate\View\View;

class PlaylistController extends Controller
{
    public function show(Playlist $playlist): View
    {
        $tracks = $playlist->track()->paginate(25);
        return view('playlist.show',['playlist' => $playlist, 'tracks' => $tracks] );
    }
}

app/Http/Controllers/TrackController.php
<?php

namespace App\Http\Controllers;

use App\Models\Track;
use Illuminate\Http\Request;
use App\Services\TrackService;
use Illuminate\View\View;

class TrackController extends Controller
{
    public function index(): View
    {
        $tracks = Track::paginate(25);
        return view('tracks.index')->with(['tracks' => $tracks]);
    }

    public function show(Track $track): View
    {
        $track->load('playlist', 'genre', 'album');
        return view('tracks.show')->with(['track' => $track]);
    }
}

resources/views/album/show.blade.php
@extends('layout.layout')

@section('content')

        <h2>Name album {{$album->title}}</h2>
        <h2>Name artist {{$album->artist->name}}</h2>
        <div class="table-responsive">
            <ul>
                @foreach($album->track as $track)
                <li>
                        <a href="{{route('track.show', $track->id)}}">{{ $track->name }}</a>
                </li>
                @endforeach
            </ul>



        </div>


@endsection

resources/views/artists/index.blade.php
@extends('layout.layout')

@section('content')


        <h2>Artist</h2>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Name</th>
                </tr>
                </thead>
                <tbody>
                @foreach($artists as $artist)
                    <tr>
                        <td><a href="{{route('artist.show', $artist->id)}}">{{ $artist->id }}</a></td>
                        <td><a href="{{route('artist.show', $artist->id)}}">{{ $artist->name }}</a></td>
                    </tr>

                @endforeach
                </tbody>
            </table>
        </div>


@endsection

resources/views/artists/show.blade.php
@extends('layout.layout')

@section('content')

        <h2>Artist</h2>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <tr>
                    <td scope="col">id</td>
                    <td><p>{{ $artist['id'] }}</p></td>

                </tr>

                <tr>
                    <td scope="col">Name</td>
                    <td><p>{{ $artist['name'] }}</p></td>
                </tr>
                @foreach($artist->album as $album)
                <tr>
                    <td scope="col">Album title</td>
                    <td scope="col">
                            <a href="{{route('album.show', $album->id)}}">{{ $album->title }}</a>
                    </td>
                </tr>
                @endforeach

            </table>

        </div>


@endsection

resources/views/layout/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{{route('track.index')}}">Audio Catalog</a>
</header>
<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{route('track.index')}}">
                            <span data-feather="{{route('track.index')}}"></span>
                            Track
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('artist.index')}}">
                            <span data-feather="{{route('artist.index')}}"></span>
                            Artist
                        </a>
                    </li>

                </ul>


            </div>
        </nav>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

        @yield('content')

        </main>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/playlist/show.blade.php
@extends('layout.layout')

@section('content')

        <h2>Name playlist {{$playlist->name}}</h2>

        <div class="table-responsive">
            <ul>
                @foreach($tracks as $track)
                <li>
                        <a href="{{route('track.show', $track->id)}}">{{ $track->name }}</a>
                </li>
                @endforeach
            </ul>
            {!! $tracks->links('pagination::bootstrap-4') !!}

        </div>


@endsection

resources/views/tracks/index.blade.php
@extends('layout.layout')

@section('content')
    <h2>Tracks</h2>
    <table class="table">
        <tr>
            <th>Track ID</th>
            <th>Name</th>
            <th>Composer</th>
            <th>Milliseconds</th>
            <th>Bytes</th>
            <th>Price</th>
        </tr>

        @foreach($tracks as $track)
            <tr>
                <td><p>{{ $track['id'] }}</p></td>
                <td><a href="{{route('track.show', $track->getKey())}}">{{ $track->name }}</a></td>
                <td><p>{{ $track->composer ?? 'No composer' }}</p></td>
                <td><p>{{ $track->milliseconds }}</p></td>
                <td><p>{{ $track->bytes }}</p></td>
                <td><p>{{ $track->unit_price }}</p></td>
            </tr>

        @endforeach

    </table>
    <br>
    {!! $tracks->links('pagination::bootstrap-4') !!}

@endsection

resources/views/tracks/show.blade.php
@extends('layout.layout')

@section('content')
        <h2>{{$track->name}}</h2>

    <table border="1">
    <tr>
        <td><p>Id</p></td>
        <td><p>{{ $track->id }}</p></td>
    </tr>
    <tr>
        <td><p>Name</p></td>
        <td><p>{{ $track->name }}</p></td>
    </tr>
    <tr>
        <td><p>Composer</p></td>
        <td><p>{{ $track->composer ?? 'No composer' }}</p></td>
    </tr>
    <tr>
        <td><p>Milliseconds</p></td>
        <td><p>{{$track->time }}</p></td>
    </tr>
    <tr>
        <td><p>Bytes</p></td>
        <td><p>{{ $track->mb }}</p></td>
    </tr>
    <tr>
        <td><p>Price</p></td>
        <td><p>{{ $track->unit_price }}</p></td>
    </tr>
        <tr>
            <td><p>Genre</p></td>
            <td><p>{{ $track->genre->name }}</p></td>
        </tr>

</table>

        <div>
            <h2>Playlists</h2>
            <ul>
                @foreach($track->playlist as $playlist)
                    <li>
                        <a href="{{route('playlist.show', $playlist->getKey())}}">{{$playlist->name}}</a>

                    </li>
                @endforeach
            </ul>
        </div>
        <div>
            <h2>Artist name</h2>
            <ul>
                    <li>
                        <a href="{{route('artist.show', $track->album->artist->getKey())}}">{{$track->album->artist->name}}</a>

                    </li>
            </ul>
        </div>


@endsection